Upgrade luajava upgrade gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -87,12 +87,16 @@ jobs:
       - name: Windows - Make
         if: runner.os == 'Windows'
         run: cd luajava && make COMMAND=.\gradlew
-
+      - name: Rename build output directory
+        run: |
+          mkdir ${{ runner.os }}
+          mv ${{ github.workspace }}/luajava/build/outputs/* ${{ runner.os }}
+          mv ${{ runner.os }} ${{ github.workspace }}/luajava/build/outputs/
       - name: Upload Build Artifact
         uses: actions/upload-artifact@v4.6.2
         with:
           name: luajava-dynamic-libraries-${{ runner.os }}
-          path: "${{ github.workspace }}/luajava/build/outputs"
+          path: "${{ github.workspace }}/outputs"
 
   build-cffi:
     strategy:
@@ -160,6 +164,44 @@ jobs:
           name: cffi-dynamic-libraries-${{ runner.os }}-${{ matrix.Lua }}
           path: "${{ github.workspace }}/cffi-lua/build/cffi"
 
+  collect-luajava:
+
+    runs-on: ubuntu-latest
+    needs: build-luajava
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: '21'
+      - name: Download Plugin Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: plugin
+          name: LuaInMinecraftBukkitII-java-8
+      - name: Download Luajava Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: luajava-dynamic-libraries
+          pattern: luajava-dynamic-libraries-*
+          merge-multiple: true
+      - run: ls -R luajava-dynamic-libraries
+      - run: |
+          mkdir -p output/linux/amd64 || echo "Failed mkdir for linux"
+          mv luajava-dynamic-libraries/Linux/shared/* output/linux/amd64 || echo "Failed mv to linux"
+          mkdir -p output/macos/arm64 || echo "Failed mkdir for macos"
+          mv luajava-dynamic-libraries/macOS/shared/* output/macos/arm64 || echo "Failed mv to macos"
+          mkdir -p output/windows/amd64 || echo "Failed mkdir for windows"
+          mv luajava-dynamic-libraries/Windows/shared/* output/windows/amd64 || echo "Failed mv to windows"
+          mv plugin/*-all.jar plugin/a.jar
+          java -cp plugin/a.jar org.eu.smileyik.luaInMinecraftBukkitII.NativeLoader ./output
+      - name: Upload Build Artifact
+        uses: actions/upload-artifact@v4.6.2
+        with:
+          name: luajava-dynamic-libraries-all
+          path: "${{ github.workspace }}/output"
+
   collect-cffi:
   
     runs-on: ubuntu-latest
@@ -177,7 +219,7 @@ jobs:
       - name: Upload Build Artifact
         uses: actions/upload-artifact@v4.6.2
         with:
-          name: cffi-dynamic-libraries-collected
+          name: cffi-dynamic-libraries-all
           path: "${{ github.workspace }}/cffi-dynamic-libraries"
 
   release:
